### ISSUE TITLE
Not an issue rather a Suggestion: Implementing teletext

### ISSUE THREAD

**Issue by itsdarklikehell** [zshall/program-guide#62]
Ive had another idea, what about implementing teletext buttons on the remote.
for an idea: https://zxnet.co.uk/teletext/viewer

tbh the following works quite nice:
```
  - number: 6
    abbr: NOS_TT
    name: NOS TeleText
    description: NOS TeleText
    backgroundAudio: http://radio.plaza.one/mp3
    backgroundAudioOptions:
      description: Nightwave Plaza Radio # Optional. Credits will appear in the Info OSD
      nowPlayingUrl: https://api.plaza.one/status # Optional. If the radio service you're using has a song history API you can link to it here.
      nowPlayingProvider: plaza-one # Required if using nowPlayingUrl. Only a few providers are supported right now; see the documentation for more info.
    iframe:
      # You can load up external websites using the IFrame engine
      src: https://teletekst-data.nos.nl/webplus # Required. The URL to load
      allowInteraction: true # Optional. If specified you can use your mouse or keyboard to interact with the IFrame.
  - number: 7
    abbr: ZXNET_TT
    name: ZXNet TeleText Stuff
    description: ZXNet TeleText Stuff
    backgroundAudio: http://radio.plaza.one/mp3
    backgroundAudioOptions:
      description: Nightwave Plaza Radio # Optional. Credits will appear in the Info OSD
      nowPlayingUrl: https://api.plaza.one/status # Optional. If the radio service you're using has a song history API you can link to it here.
      nowPlayingProvider: plaza-one # Required if using nowPlayingUrl. Only a few providers are supported right now; see the documentation for more info.
    iframe:
      # You can load up external websites using the IFrame engine
      src: https://zxnet.co.uk/teletext # Required. The URL to load
      allowInteraction: true # Optional. If specified you can use your mouse or keyboard to interact with the IFrame.

```
