### ISSUE TITLE
Megadrive doesnt load

### ISSUE THREAD

**Issue by itsdarklikehell** [zshall/program-guide#63]
Megadrive core does not load for me some reason.
i use: 

```
  - number: -3 # Negative numbers indicate line inputs. They don't show up on the channel guide.
    name: Megadrive
    description: Megadrive
    abbr: SEGAMD
    video-game:
      # The video-game engine allows you to run RetroArch cores via Nostalgist
      game: oldtowers.bin # The game library by default is from `retrobrews.github.io`. You can specify a game from there directly.
      console: megadrive # Required. The system to emulate. Allowable values are 'nes', 'snes', 'megadrive', 'gb', 'gbc', or 'gba'.
      # The video game engine doesn't support granular volume adjustment right now, but mute and unmute work.
```
the NES, SNES, GB and GBA cores work fine (even with my wired xbox360 controller. which is awesome!)

also would it be possible to define custom roms/folders to run for instance LSDj.gb on the gameboy or add other libretro systems? like gp32, psp etc. for instance?
im running a [retronas](https://github.com/retronas/retronas) on my network and its filled to the brim with roms/hacks and demoscene, diskmags and stuff. (most of them are TOSEC sets which are also on archive.org)
it would be awesome to be able to run those old artworks as playlists. retroarch itself uses those for rom collections like one could make with retroarch itself (it uses  the .cue .pls. m3u .lpl format playlists for loading for instance multi disks / swapping roms and isos and also for keeping track of playtime/history)
It would be really nice to be able to run [PiggyTracker fka. LitteGPTracker](https://github.com/djdiskmachine/LittleGPTracker) too in one of them.

also another cool channel you could add for example / funzies is:

```
  - number: 106
    name: SceneCity.TV
    description: SceneCity.TV
    abbr: SCNCTYTV
    video:
      volume: true # You can mute the video entirely if you want.
      provider: hls # The HTTP live streaming provider can be utilized if you have such a video stream.
      src: https://fra1-edge2.scenecity.net/origin3/demos/avc-auto_llhls.m3u8
      hlsBugFix: false # I've noticed that some HLS streams play automatically and if we attempt to play them again the video won't load. This is a workaround for that.
```
