### ISSUE TITLE
New feature found. Anarch

### ISSUE THREAD

**Issue by itsdarklikehell** [zshall/program-guide#68]
[Background](https://docs.libretro.com/library/anarch/#background)
Anarch is an extremely small, completely public domain, no-dependency, no-file, portable suckless anarcho-pacifist from-scratch 90s-style Doom clone that runs everywhere.

The Anarch core has been authored by

[Miloslav Číž](https://codeberg.org/drummyfish)
[iyzsong](https://codeberg.org/iyzsong)
The Anarch core is licensed under

[CC0](https://codeberg.org/iyzsong/anarch-libretro/src/branch/master/LICENSE)
A summary of the licenses behind RetroArch and its cores can be found [here](https://docs.libretro.com/development/licenses/).

[Features](https://docs.libretro.com/library/anarch/#features)
Frontend-level settings or features that the RVVM core respects.

An example:
```
  - number: -9
    abbr: ANARCH
    title: Currently Playing - (anarch).
    name: Anarch Emulator Channel.
    description: An example of Anarch emulator on a LINE-IN (Provided to you by nostalgist.github.io)
    video-game:
      game: https://sgtstroopwafel.hopto.org/roms/nintendo/gameboyadvance/Mother%201%2B2%20(USA)(Translated).gba
      console: anarch

```
