### ISSUE TITLE
Possble new feature: RetroAssembly.com

### ISSUE THREAD

**Issue by itsdarklikehell** [zshall/program-guide#69]
[RetroAssembly](https://github.com/arianrhodsandlot/retro-assembly)

RetroAssembly
Overview
A personal retro game collection cabinet in your browser.

Usage
Visit [retroassembly.com](https://retroassembly.com/).

Pick a method you prefer to provide your ROMs. For BIOS files, place them into a directory named system inside the directory you are picking.

You can also try the public library first if you do not have one now.

Start to play!

```
  - number: -2
    abbr: RETROASS
    name: Retro Assembly Channel. (Example)
    description: An example of Retro Assembly 
    iframe:
      src: https://retroassembly.com
      allowInteraction: true
```
